version: '3'

services:

 docker_registry:
  image: registry:2
  container_name: docker_registry
  restart: always
  ports:
    - 5000:5000
  volumes:
    - /tmp/docker_registry:/var/lib/registry
 docker_registry_ui:
  image: parabuzzle/craneoperator:latest
  container_name: docker_registry_ui
  restart: always
  ports:
    - 8086:80
  environment:
    - REGISTRY_HOST=docker_registry
    - REGISTRY_PORT=5000
    - REGISTRY_PROTOCOL=http
    - SSL_VERIVY=false
    - USERNAME=admin
    - PASSWORD=admin123
  depends_on:
    - docker_registry
